defaults:
  - common
  - _self_

name: dreamer3

# Training
max_global_step: 500000
warm_up_step: 10000
train_every: 5
train_iter: 1
log_every: 500
evaluate_every: 10000
ckpt_every: 50000

precision: 16
compile: true

batch_size: 16
batch_length: 64  # RNN sequence length
wm_optim:
  lr: 1e-4
  eps: 1e-8
  grad_clip: 1000.0
  weight_decay: 0.0
critic_optim:
  lr: 3e-5
  eps: 1e-5
  grad_clip: 100.0
  weight_decay: 0.0
actor_optim:
  lr: 3e-5
  eps: 1e-5
  grad_clip: 100.0
  weight_decay: 0.0
dataset_balance: false
rl_discount: 0.997
gae_lambda: 0.95
horizon: 15
ob_norm: false

critic:
  slow_update_weight: 0.98
  slow_update_freq: 1

critic_norm:
  update_weight: 0.95
  min_scale: 1.0
  clip_percentage_low: 0.05
  clip_percentage_high: 0.95

buffer_size: 1000000
reward_scale: 1.0

# Model
free_nats: 1.0  # 0.0 for Atari
ent_coef: 3e-4

wm:
  deter_dim: 512
  stoch_dim: 32
  stoch_discrete: 32
  activation: silu
  symlog: true
  unimix: 0.01
  learned_initial_state: true

encoder:
  image_shape: [64, 64, 3]
  kernel_size: [4, 4, 4, 4]
  stride: [2, 2, 2, 2]
  conv_dim: [3, 32, 64, 128, 256]
  cnn_act: silu
  hidden_dims: [512, 512]
  dense_act: silu
  symlog: true

decoder:
  image_shape: [64, 64, 3]
  seed_shape: [4, 4, 256]
  kernel_size: [4, 4, 4, 4]
  stride: [2, 2, 2, 2]
  conv_dim: [256, 128, 64, 32, 3]
  cnn_act: silu
  hidden_dims: [512, 512]
  dense_act: silu
  image_loss: mse
  state_loss: symlog_mse

actor_head:
  hidden_dims: [512, 512]
  activation: silu

critic_head:
  hidden_dims: [512, 512]
  activation: silu
  loss: symlog_discrete

reward_head:
  hidden_dims: [512, 512]
  activation: silu
  loss: symlog_discrete

cont_head:
  hidden_dims: [512, 512]
  activation: silu
  loss: binary


