defaults:
  - algo@rolf: ppo
  - env: default
  - _self_
  - override hydra/hydra_logging: none
  - override hydra/job_logging: stdout


# Training
seed: 123
is_train: true
init_ckpt_path: null
init_ckpt_pretrained: false
gpu: null
pretrain: false

# Evaluation
ckpt_num: null
num_eval: 1
record_video: true
record_extra: false
record_video_caption: true
record_demo: false

# Log
run_prefix: null
notes: null
log_root_dir: log
wandb: false
wandb_entity: null
wandb_project: null

# Hydra
hydra:
  output_subdir: null
  run:
    dir: .
